title: Max Tassano
author: GitHub User
email: max.tassano@gmail.com
description: This is a test site for Max Tassano to experiment and learn web design

# social links
twitter_username: MaxTassano # DO NOT include the @ character, or else the build will fail!
github_username:  maxtassano # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
